stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/data.pkl
    outs:
    - data/raw/data.pkl

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/data.pkl
    outs:
    - data/processed/train_data.pkl
    - data/processed/test_data.pkl

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_data.pkl
    - data/processed/test_data.pkl
    - src/train_and_evaluate.py
    params:
    - estimators.cnn.params.epochs
    - estimators.cnn.params.batch_size
#    metrics:
#    - report/scores.json:
#        cache: false
#    - report/params.json:
#        cache: false
#    outs:
#    - saved_models/model.h5

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
    - src/log_production_model.py