base:
  project: mlops-project
  random_state: 1
  target_col: TARGET

data_source:
  sem_source: data_given/data.pkl

load_data:
  raw_dataset: data/raw/data.pkl

split_data:
  train_path: data/processed/train_data.pkl
  test_path: data/processed/test_data.pkl
  test_size: 0.2
  train_size: 0.8

estimators:
  cnn:
    params:
      epochs: 2
      batch_size: 10
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.h5

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: mlops_cps
  run_name: mlops
  registered_model_name: cnnModel
  remote_server_uri: http://0.0.0.0:5001